export const FILE_UPLOAD_REQUEST = "FILE_UPLOAD_REQUEST"
export const FILE_UPLOAD_SUCCESS = "FILE_UPLOAD_SUCCESS"
export const FILE_UPLOAD_FAILURE = "FILE_UPLOAD_FAILURE"

export const FILE_DOWNLOAD_REQUEST = "FILE_DOWNLOAD_REQUEST"
export const FILE_DOWNLOAD_SUCCESS = "FILE_DOWNLOAD_SUCCESS"
export const FILE_DOWNLOAD_FAILURE = "FILE_DOWNLOAD_FAILURE"

export const FILE_CLEAR = "FILE_CLEAR"