export const IMAGE_UPLOAD_REQUEST = "IMAGE_UPLOAD_REQUEST"
export const IMAGE_UPLOAD_SUCCESS = "IMAGE_UPLOAD_SUCCESS"
export const IMAGE_UPLOAD_FAILURE = "IMAGE_UPLOAD_FAILURE"

export const IMAGE_DOWNLOAD_REQUEST = "IMAGE_DOWNLOAD_REQUEST"
export const IMAGE_DOWNLOAD_SUCCESS = "IMAGE_DOWNLOAD_SUCCESS"
export const IMAGE_DOWNLOAD_FAILURE = "IMAGE_DOWNLOAD_FAILURE"