export const PORTFOLIO_DOWNLOAD_REQUEST = "PORTFOLIO_DOWNLOAD_REQUEST"
export const PORTFOLIO_DOWNLOAD_SUCCESS = "PORTFOLIO_DOWNLOAD_SUCCESS"
export const PORTFOLIO_DOWNLOAD_FAILURE = "PORTFOLIO_DOWNLOAD_FAILURE"